package org.woped.woflan;

//! Describes an arc in the reachability graph
//! Such an arc can be used to get the follow-up marking
//! that is the destination of the arc
//! A set of reachability arcs is generated by the Marking object
public class ReachabilityArc {

	public ReachabilityArc() {}
	
	

}
