package org.woped.core.controller;

/**
 * This interface is used for receiving ViewEvents generated by ViewControllers
 * and ApplicationMediators.The listener is be called on the viewEventPerformed
 * method.
 */
public interface IViewListener
{

    /**
     * Invoked directly when a ViewEvent has been fired.
     */
    public abstract void viewEventPerformed(AbstractViewEvent viewevent);

}
