
package org.woped.qualanalysis.paraphrasing.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProcessToTextImplService", targetNamespace = "http://server/", wsdlLocation = "http://ai.wu.ac.at/ProcessToTextService/ProcessToText?wsdl")
public class ProcessToTextImplService
    extends Service
{

    private final static URL PROCESSTOTEXTIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.woped.qualanalysis.paraphrasing.webservice.ProcessToTextImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.woped.qualanalysis.paraphrasing.webservice.ProcessToTextImplService.class.getResource(".");
            url = new URL(baseUrl, "http://ai.wu.ac.at/ProcessToTextService/ProcessToText?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://ai.wu.ac.at/ProcessToTextService/ProcessToText?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PROCESSTOTEXTIMPLSERVICE_WSDL_LOCATION = url;
    }

    public ProcessToTextImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessToTextImplService() {
        super(PROCESSTOTEXTIMPLSERVICE_WSDL_LOCATION, new QName("http://server/", "ProcessToTextImplService"));
    }

    /**
     * 
     * @return
     *     returns ProcessToText
     */
    @WebEndpoint(name = "ProcessToTextImplPort")
    public ProcessToText getProcessToTextImplPort() {
        return super.getPort(new QName("http://server/", "ProcessToTextImplPort"), ProcessToText.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessToText
     */
    @WebEndpoint(name = "ProcessToTextImplPort")
    public ProcessToText getProcessToTextImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "ProcessToTextImplPort"), ProcessToText.class, features);
    }

}
