//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.18 at 08:57:29 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.yawlfoundation.org/yawlschema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.woped.file.yawl.model;
