//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.18 at 08:57:29 AM CEST 
//


package org.woped.file.yawl.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourcingAllocateFactsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourcingAllocateFactsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.yawlfoundation.org/yawlschema}ResourcingInteractionInitiatorType">
 *       &lt;sequence>
 *         &lt;element name="allocator" type="{http://www.yawlfoundation.org/yawlschema}ResourcingSelectorFactsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourcingAllocateFactsType", propOrder = {
    "allocator"
})
public class ResourcingAllocateFactsType
    extends ResourcingInteractionInitiatorType
{

    protected ResourcingSelectorFactsType allocator;

    /**
     * Gets the value of the allocator property.
     * 
     * @return
     *     possible object is
     *     {@link ResourcingSelectorFactsType }
     *     
     */
    public ResourcingSelectorFactsType getAllocator() {
        return allocator;
    }

    /**
     * Sets the value of the allocator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourcingSelectorFactsType }
     *     
     */
    public void setAllocator(ResourcingSelectorFactsType value) {
        this.allocator = value;
    }

}
